jobs:
  include:
    - stage: Test
      language: java
      dist: xenial
      jdk: oraclejdk9
      install:
        - gradle assemble
      script:
        - gradle run

stages:
  - Test
branches:
  only:
    - /.*/
notifications:
  email: false
